name: Docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install . sphinx==5.3.0 numpy scipy numpydoc pydata-sphinx-theme
      - name: Sphinx build
        run: |
          sphinx-build -E -b html docs/source build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          cname: repliclust.org
          force_orphan: true